# Generated by Django 4.1.2 on 2023-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.FloatField(default=1000000),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pnl",
            field=models.FloatField(default=0.0),
        ),
    ]
