# Generated by Django 4.1.2 on 2023-01-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customuser_balance_customuser_pnl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(default="", max_length=32)),
            ],
        ),
    ]
