# Generated by Django 4.1.2 on 2023-01-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="desc",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="asset",
            name="exchange_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="image_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="asset",
            name="instrument_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="instrument_type",
            field=models.CharField(default="", max_length=1),
        ),
    ]
