# Generated by Django 4.1.2 on 2023-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_asset_listed_asset_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="perc_change",
            field=models.FloatField(default=0.0),
        ),
    ]
