# Generated by Django 4.1.2 on 2023-01-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_asset_perc_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="volume",
            field=models.FloatField(default=0.0),
        ),
    ]
