# Generated by Django 4.1.2 on 2023-01-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_asset_volume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="image_url",
        ),
    ]
