# Generated by Django 4.1.2 on 2023-01-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_asset_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_id", models.IntegerField(default=0)),
                ("user_id", models.IntegerField(default=0)),
                ("tf", models.CharField(default="1D", max_length=4)),
            ],
        ),
    ]
