# Generated by Django 4.1.2 on 2023-01-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_chart"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="indicators",
            field=models.JSONField(default={}),
        ),
    ]
