# Generated by Django 4.1.2 on 2023-01-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_chart_indicators"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chart",
            old_name="indicators",
            new_name="settings",
        ),
    ]
