# Generated by Django 4.1.2 on 2023-01-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_rename_indicators_chart_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="price_change",
            field=models.FloatField(default=0.0),
        ),
    ]
