# Generated by Django 4.1.2 on 2023-01-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_asset_price_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_market_open",
            field=models.BooleanField(default=False),
        ),
    ]
