# Generated by Django 4.1.2 on 2023-01-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_asset_is_market_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="daily_close_price",
            field=models.FloatField(default=0.0),
        ),
    ]
