# Generated by Django 4.1.2 on 2023-01-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_asset_daily_close_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_id", models.IntegerField(default=0)),
                ("price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="price",
        ),
    ]
