# Generated by Django 4.1.2 on 2023-01-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_asset_price_remove_asset_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="is_market_open",
        ),
        migrations.AddField(
            model_name="asset_price",
            name="is_market_open",
            field=models.BooleanField(default=False),
        ),
    ]
