# Generated by Django 4.1.2 on 2023-01-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_remove_asset_is_market_open_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset_price",
            old_name="price",
            new_name="ask_price",
        ),
        migrations.AddField(
            model_name="asset_price",
            name="bid_price",
            field=models.FloatField(default=0.0),
        ),
    ]
