# Generated by Django 4.1.2 on 2023-01-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_rename_price_asset_price_ask_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField(default=0)),
            ],
        ),
    ]
