# Generated by Django 4.1.2 on 2023-01-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_mo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mo",
            name="t",
            field=models.IntegerField(default=0),
        ),
    ]
