# Generated by Django 4.1.2 on 2023-01-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_rename_price_asset_ask_price_asset_bid_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset_price",
            name="precision",
            field=models.IntegerField(default=0),
        ),
    ]
