# Generated by Django 4.1.2 on 2023-01-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_asset_price_precision"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mo",
        ),
    ]
