# Generated by Django 4.1.2 on 2023-01-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_delete_mo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset_price",
            name="precision",
        ),
        migrations.AddField(
            model_name="asset",
            name="precision",
            field=models.IntegerField(default=0),
        ),
    ]
