# Generated by Django 4.1.2 on 2023-01-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_remove_asset_price_precision_asset_precision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="ask_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="bid_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="daily_close_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="perc_change",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="price_change",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="volume",
        ),
        migrations.AlterField(
            model_name="asset",
            name="desc",
            field=models.TextField(default=""),
        ),
    ]
