# Generated by Django 4.1.2 on 2023-01-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_delete_asset_price_asset_close_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="perc_change",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="asset",
            name="price_change",
            field=models.FloatField(default=0.0),
        ),
    ]
