# Generated by Django 4.1.2 on 2023-01-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_asset_perc_change_asset_price_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="close_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="is_market_open",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="perc_change",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="price_change",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="volume",
        ),
    ]
