# Generated by Django 4.1.2 on 2023-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_remove_asset_close_price_remove_asset_is_market_open_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsocketConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_id", models.IntegerField(default=0)),
                ("tf", models.CharField(default="", max_length=32)),
            ],
        ),
    ]
