# Generated by Django 4.1.2 on 2023-01-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_websocketconnection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebsocketConnection",
        ),
        migrations.AddField(
            model_name="asset",
            name="bid_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="close_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="daily_volume",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_market_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset",
            name="official_close_price",
            field=models.FloatField(default=0),
        ),
    ]
