# Generated by Django 4.1.2 on 2023-01-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_delete_websocketconnection_asset_bid_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="daily_volume",
            field=models.FloatField(default=None),
        ),
    ]
