# Generated by Django 4.1.2 on 2023-01-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_alter_asset_daily_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="ask_price",
            field=models.FloatField(default=0),
        ),
    ]
