# Generated by Django 4.1.2 on 2023-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_asset_ask_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(null=True)),
                ("status", models.CharField(default="p", max_length=1)),
                ("iid", models.IntegerField(default=0)),
                ("asset_name", models.CharField(default="", max_length=64)),
                ("order_type", models.CharField(default="m", max_length=1)),
                ("side", models.CharField(default="l", max_length=1)),
                ("price", models.FloatField(default=0)),
                ("size", models.FloatField(default=0)),
                ("size_type", models.CharField(default="t", max_length=1)),
            ],
        ),
    ]
