# Generated by Django 4.1.2 on 2023-01-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="leverage",
            field=models.IntegerField(default=1),
        ),
    ]
