# Generated by Django 4.1.2 on 2023-01-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_position_alter_asset_last_update_current_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="leverage",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 24, 17, 2, 44, 86105)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 24, 17, 2, 44, 86088)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 24, 17, 2, 44, 86100)
            ),
        ),
    ]
