# Generated by Django 4.1.2 on 2023-01-24 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_position_leverage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="calc_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 25, 20, 13, 2, 36077)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 25, 20, 13, 2, 36058)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 25, 20, 13, 2, 36071)
            ),
        ),
    ]
