# Generated by Django 4.1.2 on 2023-01-29 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_rename_initial_bid_price_position_dollar_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="exchange_id",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="instrument_id",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="instrument_type",
            field=models.CharField(default="", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 18, 19, 6, 734278)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 18, 19, 6, 734262)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 18, 19, 6, 734274)
            ),
        ),
    ]
