# Generated by Django 4.1.2 on 2023-01-29 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_alter_asset_exchange_id_alter_asset_instrument_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="o_exp_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_iv",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_last_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_moneyness",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_oi",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_strike_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_type",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="asset",
            name="o_volume",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 31, 59, 429276)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 31, 59, 429258)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 31, 59, 429271)
            ),
        ),
    ]
