# Generated by Django 4.1.2 on 2023-01-29 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_asset_o_exp_date_asset_o_iv_asset_o_last_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(default="", max_length=32)),
                ("desc", models.TextField(default="")),
                ("price", models.FloatField(default=0)),
                ("strike_price", models.FloatField(default=0)),
                ("type", models.CharField(default="", max_length=1)),
                ("moneyness", models.FloatField(default=0)),
                ("exp_date", models.DateTimeField(default=None, null=True)),
                ("last_price", models.FloatField(default=0)),
                ("volume", models.IntegerField(default=0)),
                ("oi", models.IntegerField(default=0)),
                ("iv", models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_exp_date",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_iv",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_last_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_moneyness",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_oi",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_strike_price",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_type",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="o_volume",
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 50, 28, 323103)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 50, 28, 323044)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 50, 28, 323055)
            ),
        ),
    ]
