# Generated by Django 4.1.2 on 2023-01-29 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_option_remove_asset_o_exp_date_remove_asset_o_iv_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="type",
            new_name="option_type",
        ),
        migrations.AddField(
            model_name="option",
            name="ask_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="option",
            name="bid_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="option",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 1, 21, 52, 8, 659936)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 52, 8, 659686)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 52, 8, 659625)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 52, 8, 659637)
            ),
        ),
    ]
