# Generated by Django 4.1.2 on 2023-01-29 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_rename_type_option_option_type_option_ask_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 55, 53, 393226)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 55, 53, 393208)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 30, 21, 55, 53, 393221)
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 1, 21, 55, 53, 393495)
            ),
        ),
    ]
