# Generated by Django 4.1.2 on 2023-01-30 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_alter_asset_last_update_current_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="listed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_current_price",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 31, 1, 21, 50, 16206)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_daily_volume",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 31, 1, 21, 50, 16190)
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="last_update_is_market_open",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 31, 1, 21, 50, 16201)
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 2, 1, 21, 50, 16474)
            ),
        ),
    ]
